//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace SMT.SaaS.OA.UI.AgentChannel {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EMPLOYEECHANGEHISTORY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EMPLOYEECHECK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_ASSESSMENTFORMMASTER))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_ASSESSMENTFORMDETAIL))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_CHECKPOINTSET))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_CHECKPOINTLEVELSET))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_CHECKPROJECTSET))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EMPLOYEEPOSTCHANGE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EMPLOYEECONTRACT))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EMPLOYEEENTRY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EMPLOYEEINSURANCE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EMPLOYEEPOST))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_LEFTOFFICE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_LEFTOFFICECONFIRM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_POST))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_DEPARTMENT))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_COMPANY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_COMPANYHISTORY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_DEPARTMENTDICTIONARY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_DEPARTMENTHISTORY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_POSTDICTIONARY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_POSTHISTORY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_RELATIONPOST))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_FAMILYMEMBER))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_PENSIONMASTER))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_PENSIONDETAIL))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_RESUME))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EDUCATEHISTORY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EXPERIENCE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EMPLOYEE))]
    public partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EMPLOYEECHANGEHISTORY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EMPLOYEECHECK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_ASSESSMENTFORMMASTER))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_ASSESSMENTFORMDETAIL))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_CHECKPOINTSET))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_CHECKPOINTLEVELSET))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_CHECKPROJECTSET))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EMPLOYEEPOSTCHANGE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EMPLOYEECONTRACT))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EMPLOYEEENTRY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EMPLOYEEINSURANCE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EMPLOYEEPOST))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_LEFTOFFICE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_LEFTOFFICECONFIRM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_POST))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_DEPARTMENT))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_COMPANY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_COMPANYHISTORY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_DEPARTMENTDICTIONARY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_DEPARTMENTHISTORY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_POSTDICTIONARY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_POSTHISTORY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_RELATIONPOST))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_FAMILYMEMBER))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_PENSIONMASTER))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_PENSIONDETAIL))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_RESUME))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EDUCATEHISTORY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EXPERIENCE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMT.SaaS.OA.UI.AgentChannel.T_HR_EMPLOYEE))]
    public partial class EntityObject : SMT.SaaS.OA.UI.AgentChannel.StructuralObject {
        
        private SMT.SaaS.OA.UI.AgentChannel.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SMT.SaaS.OA.UI.AgentChannel.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_EMPLOYEECHANGEHISTORY {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_EMPLOYEECHECK {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_ASSESSMENTFORMMASTER {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_ASSESSMENTFORMDETAIL {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_CHECKPOINTSET {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_CHECKPOINTLEVELSET {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_CHECKPROJECTSET {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_EMPLOYEEPOSTCHANGE {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_EMPLOYEECONTRACT {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_EMPLOYEEENTRY {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_EMPLOYEEINSURANCE {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_EMPLOYEEPOST {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_LEFTOFFICE {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_LEFTOFFICECONFIRM {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_POST {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_DEPARTMENT {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_COMPANY {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_COMPANYHISTORY {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_DEPARTMENTDICTIONARY {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_DEPARTMENTHISTORY {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_POSTDICTIONARY {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_POSTHISTORY {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_RELATIONPOST {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_FAMILYMEMBER {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_PENSIONMASTER {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_PENSIONDETAIL {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_RESUME {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_EDUCATEHISTORY {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class T_HR_EXPERIENCE {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_HR_EMPLOYEE", Namespace="http://schemas.datacontract.org/2004/07/TM_SaaS_OA_EFModel", IsReference=true)]
    public partial class T_HR_EMPLOYEE {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class EntityKey {
    }
}
